### PR TITLE
Use Knife's cooldown instead of a timed attack.

### PR DESCRIPTION
**Pull request by xAstroBoy**
Title, makes it way faster and reliable.

### CODE REVIEW

**Comment by Yan01h** [comment]
Can you explain how that makes it faster and more reliable? From the tests i did the hits wouldn't count anymore if i would hit only a little bit faster since the delay. Haven't tested it much online tho.

**Comment by AbandonedAccount1111** [comment]
> Can you explain how that makes it faster and more reliable? From the tests i did the hits wouldn't count anymore if i would hit only a little bit faster since the delay. Haven't tested it much online tho.

it relies on how a client set the cooldown, not just  a hardcoded one.
Nevermind, i see you dug in Knife 's class and used timeAtLastDamageDealt, technically is possible to bypass that.

**Comment by Yan01h** [comment]
With bypass you mean hit faster while the hits are also working?

**Comment by AbandonedAccount1111** [comment]
> With bypass you mean hit faster while the hits are also working?

yeah, you can set it by patching HitKnife and setting timeAtLastDamageDealt to 0, which removes effectively the knife cooldown for hit damage, and if you spam click it will always deal damage.

**Comment by Yan01h** [comment]
Yea, have already tried that but i would just count that as cheating. I mean a auto clicker is technically cheating as well but swinging at certain intervals is something everybody can do

**Comment by Yan01h** [comment]
I'm going to close this for now since i don't see any reason to change this yet.

**Pull request closed without merging**
